### ISSUE TITLE
where is the UTR code for KGET task?

### ISSUE THREAD

**Issue by zhiweihu1103** [RaynorLEE/ENGG5104_ass2#1]
Hi, folk, nice work. I cannot open issue in [KG-EntityTyping](https://github.com/RaynorLEE/KG-EntityTyping) , I want to know where is the UTR code for KGET task?

**Comment by RaynorLEE** [comment]
Hi Zhiwei,

It is included in the run_ska.py file.
Regarding issues about the SSET project, you can directly email me via the
email listed in the paper.

Best,
Muzhi

--

Zhiwei Hu ***@***.***> 於 2024年4月22日週一 下午4:46寫道：
